### ISSUE TITLE
dfrobot _ina 219

### ISSUE THREAD

**Issue by cristeamihai** [DFRobot/DFRobot_INA219#2]
the provided code is not working with python either python 3

error get when python  

pi@raspberrypi:~/DFRobot_INA219/Python/RespberryPi $ python get_voltage_current_power.py
Traceback (most recent call last):
  File "get_voltage_current_power.py", line 29, in <module>
    while not ina.begin():
  File "/home/pi/DFRobot_INA219/Python/RespberryPi/DFRobot_INA219.py", line 69, in begin
    self.set_bus_ADC(self.adc_bits_12, self.adc_sample_8)
  File "/home/pi/DFRobot_INA219/Python/RespberryPi/DFRobot_INA219.py", line 118, in set_bus_ADC
    if(bits < adc_bits_12 and sample > adc_sample_1):
NameError: global name 'adc_bits_12' is not defined

found working code at  pi-ina219 1.3.0

**Comment by Sincoster** [comment]
I have that same problem.

Now i test what you found.

**Comment by KrzysztofSikora** [comment]
I have the same problem. Could you add better documentation?

**Comment by cristeamihai** [comment]
Just look for common library and example for raspi ina219 ic, the moded code I ve losted. Now use current to voltage analog. I'll put moded code if I LL found on computer. Good luck

**Comment by KrzysztofSikora** [comment]
@cristeamihai Thanks for your help. I've found library and the code works.
https://github.com/chrisb2/pi_ina219



```
#!/usr/bin/env python
from ina219 import INA219
from ina219 import DeviceRangeError

SHUNT_OHMS = 0.1


def read():
    ina = INA219(SHUNT_OHMS, address=0x45)
    ina.configure()

    print("Bus Voltage: %.3f V" % ina.voltage())
    try:
        print("Bus Current: %.3f mA" % ina.current())
        print("Power: %.3f mW" % ina.power())
        print("Shunt voltage: %.3f mV" % ina.shunt_voltage())
    except DeviceRangeError as e:
        # Current out of device range with specified shunt resistor
        print(e)


if __name__ == "__main__":
    read()
```
